<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMainPagesForUser(User $user){
        /** @var ArrayCollection $allPages */
        $allPages =  $this->findBy(['main'=>true]);

        if($user->hasRole('ROLE_ACCESS_TO_EDIT_ALL_PAGES') || $user->hasRole('ROLE_ADMIN')){
            return $allPages;
        }

        foreach ($allPages as $page) {
            if(!$user->getEditablePages()->contains($page) && !$this->hasAccessToSubPage($user->getEditablePages(),$page)){
                foreach ($allPages as $key=>$item){
                    if($item->getId() === $page->getId()){
                       unset($allPages[$key]);
                    }
                }
            }
        }

        return $allPages;
    }
    private function hasAccessToSubPage($userPages, $page){

        foreach ($page->getSubPages() as $subPage){
            if($userPages->contains($subPage)){
                return true;
            }
        }
        return false;
    }
}
