<?php

namespace AppBundle\Repository;

/**
 * SubPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubPageRepository extends \Doctrine\ORM\EntityRepository
{
}
