# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
            ROLE_ADMIN:  [
                ROLE_USER,
                ROLE_ACCESS_TO_VIEW_ALL_PAGES,
                ROLE_ACCESS_TO_EDIT_ALL_PAGES,
                ROLE_ADD_PAGE,
                ROLE_ADD_LIBRARY,
                ROLE_EDIT_LIBRARY,
                ROLE_PERMISSION_PANEL
              ]


    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            access_denied_handler: AppBundle\Security\AccessDeniedHandler
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                always_use_default_target_path: false
                default_target_path: homepage
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/(%app_locales%)/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/(%app_locales%)/register, role: ROLE_ADMIN }
#        - { path: ^/%app_locales%/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(%app_locales%)/admin/, roles: ROLE_ADMIN }
        - { path: ^/(%app_locales%)/library/new, roles: ROLE_ADD_LIBRARY }
        - { path: ^/(%app_locales%)/page/new, roles: ROLE_ADD_PAGE }
        - { path: ^/(%app_locales%)/subpage/[0-9]+/new, roles: ROLE_ADD_PAGE }
        - { path: ^/(%app_locales%)/library/[0-9]+/edit, roles: ROLE_EDIT_LIBRARY }
        - { path: ^/(%app_locales%)/library/[0-9]+/delete, roles: ROLE_EDIT_LIBRARY }
        - { path: ^/(%app_locales%)/user/, roles: ROLE_PERMISSION_PANEL }
        - { path: ^/(%app_locales%)/library/, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/(%app_locales%)/page/, roles: IS_AUTHENTICATED_FULLY }
