user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  [GET,POST]

user_change_status:
  path: /{id}/changeStatus
  defaults: { _controller: "AppBundle:User:changeStatus" }
  methods:  [POST]

user_permissions:
    path:     /{id}/permissions
    defaults: { _controller: "AppBundle:User:permissions" }
    methods:  [GET,POST]