app_subpage:
    resource: "@AppBundle/Resources/config/routing/subpage.yml"
    prefix:   /subpage


#------------------ fos_user --------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


#---------------------------------------------------

homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  [GET,POST]

default_service:
    path:     /service
    defaults: { _controller: "AppBundle:Default:service" }
    methods:  [GET]

default_service_convert:
    path:     /service/convert
    defaults: { _controller: "AppBundle:Default:serviceConvert" }
    methods:  [GET,POST]


app_bundle_page:
    resource: "@AppBundle/Resources/config/routing/page.yml"
    prefix: /page

app_bundle_subpage:
    resource: "@AppBundle/Resources/config/routing/subpage.yml"
    prefix: /subpage

app_bundle_library:
    resource: "@AppBundle/Resources/config/routing/library.yml"
    prefix: /library

app_bundle_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user


app_bundle_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix: /contact