AppBundle\Entity\User:
    type:  entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
        availablePages:
            targetEntity: Page
            cascade: ["persist","refresh"]
            joinTable:
                name: pages_users_permission
                nullable: true
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'
                inverseJoinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'

        editablePages:
            targetEntity: Page
            cascade: ["persist","refresh"]
            joinTable:
                name: pages_users_edit_permission
                nullable: true
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'
                inverseJoinColumns:
                    page_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'